name: WebAssembly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on:  ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Cargo component
      run: |
        cargo install cargo-component
    - name: Check
      run: |
        cargo clippy --target wasm32-wasi --all-targets --all-features -- --deny warnings --deny clippy::all --deny clippy::pedantic --deny clippy::nursery --deny clippy::cargo
        cargo fmt --check
    - name: Build
      run: cargo component build --verbose
    - name: Run tests
      run: cargo component test --verbose
